version: "3.4"

services:
  api_redis:
    ports:
      - "5150:8080"
      - "5151:8081"
    image: api_redis
    build:
      context: .
      dockerfile: API_Redis/Dockerfile
    depends_on:
      - redis   
  redis_cache:
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    